### ISSUE TITLE
Choose the C++ standard

### ISSUE THREAD

**Issue by flaviojs** [zrax/string_theory#14] opened 2019-11-03 13:53 UTC
Hi there, I tried out 2.3 and I really like this library.

In my case I need to enforce C++11, but CMakeLists.txt chooses the latest available.
I get around it by building as an external project and replacing the CMakeLists.txt in the patch step, with stuff related to newer standards removed.
Ideally there would be an option that lets me restrict the features to C++11.

**Comment by zrax** [comment] 2019-11-04 23:42
Hmm, ideally the library would be compiled with the latest supported standard, but will still be usable when the compiler is set to use an older standard.  We've already fixed a couple of cases of that (mostly with C++17 library features)...  Are you seeing specific issues with using ST in C++11 mode after building it against a newer standard?

**Comment by flaviojs** [comment] 2019-11-05 01:42
I did not try and will not use it like that.
Weird issues tend to pop up when you start mixing things.
I'm matching everything that is compiled by the build system to avoid them.

**Comment by flaviojs** [comment] 2019-11-05 06:03
Btw, the current [CMakeLists.txt](https://github.com/zrax/string_theory/blob/19f9576167ac5ca0dce9ead7d8099f33aa7e0b50/CMakeLists.txt) seems to assume that try_compile will honor CMAKE_CXX_STANDARD but that is only true for cmake 3.8+.

Maybe your minimum cmake version needs to be bumped to 3.8?

**Comment by zrax** [comment] 2019-11-05 23:34
For the string_theory-2 branch, I've implemented a new `ST_CXX_STANDARD` cmake flag which can be set to a specific version, with the default being `latest` to match current behavior.

For the master branch (to be 3.0), the problem is a little different.  For one thing, master is now header-only, meaning the selected C++ standard only affects the generated st_config.h and the unit tests.  There are also significantly fewer try_compile features in master, since we bumped up the minimum compiler requirements to those supporting all of C++11.  I'm aware of the problem with try_compile, but I believe it to be less important on master, since the newer compilers (those for whom the CMAKE_CXX_STANDARD setting is more likely to matter) usually come with newer CMake versions as well.  Moreover, the only effect of having the detection wrong is that you might end up with an st_config.h that disables some features your compiler might otherwise support.

Ideally, I'd like to eventually have a fully static set of headers that can be used without cmake, and only use cmake for building the unit tests (at which point selecting only the latest C++ standard would be appropriate since it would only affect the tests).  Unfortunately, we're not there quite yet.

**Comment by flaviojs** [comment] 2019-11-06 07:53
I tried it and it seems to work fine, but I'm concerned about the filesystem library in gnu.

I want the std::string stuff but not filesystem.
It's fine to allow filesystem as long as it does not force adding a library I don't need.
In my gcc 5.4 it detects the experimental filesystem and does not need the library, but other versions might need it. Maybe add an option to disable the filesystem?

**Comment by zrax** [comment] 2019-11-06 19:28
Ok, should be addressed by 876cac6691238192fe7b2ddea09585d3e050cd02 -- you can set -DST_ENABLE_FILESYSTEM=OFF to disable the std::filesystem stuff (including the need for the -lstdc++fs on compiler versions that require it)

**Comment by flaviojs** [comment] 2019-11-07 15:23
Everything seems to work fine, thanks. :+1:

**Closed** 2019-11-07 16:47 UTC
